//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLGame
    {
        public Nullable<int> NFLWeekId { get; set; }
        public Nullable<System.DateTime> GameTime { get; set; }
        public Nullable<int> HomeTeamId { get; set; }
        public Nullable<int> VisitingTeamId { get; set; }
        public Nullable<int> HomeTeamScore { get; set; }
        public Nullable<int> VisitingTeamScore { get; set; }
        public int NFLGameId { get; set; }
    
        public virtual NFLTeam HomeTeam { get; set; }
        public virtual NFLTeam VisitingTeam { get; set; }
        public virtual NFLWeek NFLWeek { get; set; }
    }
}
