//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLTeam
    {
        public NFLTeam()
        {
            this.NFLGames = new HashSet<NFLGame>();
            this.NFLGames1 = new HashSet<NFLGame>();
        }
    
        public int NFLTeamId { get; set; }
        public string City { get; set; }
        public string TeamName { get; set; }
    
        public virtual ICollection<NFLGame> NFLGames { get; set; }
        public virtual ICollection<NFLGame> NFLGames1 { get; set; }
    }
}
