//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLWeek
    {
        public NFLWeek()
        {
            this.NFLGames = new HashSet<NFLGame>();
        }
    
        public int NFLWeekId { get; set; }
        public Nullable<int> NFLSeasonId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<NFLGame> NFLGames { get; set; }
        public virtual NFLSeason NFLSeason { get; set; }
    }
}
