//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.RacePicks = new HashSet<RacePick>();
        }
    
        public int RaceId { get; set; }
        public Nullable<System.DateTime> RaceDate { get; set; }
        public string RaceName { get; set; }
        public int TrackId { get; set; }
    
        public virtual ICollection<RacePick> RacePicks { get; set; }
        public virtual Track Track { get; set; }
    }
}
