//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPN.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsEntities : DbContext
    {
        public SportsEntities()
            : base("name=SportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<RacePick> RacePicks { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<RaceFinish> RaceFinishes { get; set; }
        public virtual DbSet<NFLGame> NFLGames { get; set; }
        public virtual DbSet<NFLSeason> NFLSeasons { get; set; }
        public virtual DbSet<NFLTeam> NFLTeams { get; set; }
        public virtual DbSet<NFLWeek> NFLWeeks { get; set; }
        public virtual DbSet<NFLGamePick> NFLGamePicks { get; set; }
    }
}
